services:
  robonomics-public-node:
    image: robonomics/robonomics:v3.3.0
    container_name: robonomics-public-node
    user: 4200:4200
    restart: always
    ports:
      - 30333:30333 # p2p port
      - 9944:9944 # ws port
      - 9615:9615 # Prometheus port
    volumes:
      - ${BASE_PATH}:/robonomics
    command: [
      "robonomics",
      "--chain=${CHAIN}",
      "--name=${NODE_NAME}",
      "--telemetry-url=wss://telemetry.parachain.robonomics.network/submit/ 0",
      "--base-path=/robonomics/base/",
      "--prometheus-external",
      "--rpc-external",
      "--rpc-cors=all",
      "--state-pruning=archive", 
      "--",
      "--sync=warp",
      "--prometheus-external"
    ]
