FROM certbot/certbot:v3.3.0

# Установка cron
# RUN apt-get update && apt-get install -y cron

# Копируем файл с задачами cron
COPY certbot_renew_cron /etc/cron.d/certbot_renew_cron

# Даем права на выполнение файла cron
RUN chmod 0644 /etc/cron.d/certbot_renew_cron

# Создаем папку для логов
RUN mkdir -p /var/log/cron

# Запуск cron и certbot в foreground
CMD ["sh", "-c", "cron && tail -f /var/log/cron.log"]
