services:
  robonomics-public-node:
    image: robonomics/robonomics:v3.3.0
    container_name: robonomics-public-node
    ports:
      - 30333:30333 # p2p port
      - 9944:9944 # ws port
      - 9615:9615 # Prometheus port
    volumes:
      - ${ROBONOMICS_PUBLIC_NODE_BASE_PATH}:/robonomics
    command: [
      "robonomics",
      "--chain=${CHAIN}",
      "--name=${NODE_NAME}",
      "--telemetry-url=wss://telemetry.parachain.robonomics.network/submit/ 0",
      "--base-path=/robonomics/base/",
      "--prometheus-external",
      "--rpc-external",
      "--rpc-cors=all",
      "--state-pruning=archive", 
      "--",
      "--sync=warp",
      "--prometheus-external"
    ]

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/certs:/etc/nginx/certs
      - ./files/certs/cert.pem:/etc/nginx/cert.pem
      - ./files/certs/key.pem:/etc/nginx/key.pem
      - ./files/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot:v3.3.0
    container_name: certbot
    volumes:
      - ./files/certs:/etc/nginx/certs
      - ./files/certbot/www:/var/www/certbot
      - ./files/certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_ADMIN_EMAIL} --agree-tos --non-interactive --expand --domain ${CERTBOT_DOMAIN} --dry-run
