services:
  robonomics:
    container_name: robonomics-bootnode
    image: robonomics/robonomics:v3.3.0
    user: 4200:4200
    restart: always
    ports:
      - ${PARACHAIN_P2P_PORT:-30333}:30333
      - ${PARACHAIN_WS_PORT:-9944}:9944
      - ${PARACHAIN_PROMETHEUS_PORT}:9615    
      - ${RELAYCHAIN_P2P_PORT:-30334}:30334
      - ${RELAYCHAIN_WS_PORT:-9945}:9945
      - ${RELAYCHAIN_PROMETHEUS_PORT}:9616
    volumes:
      - ${BASE_PATH}:/robonomics
    command: [
      "robonomics",
      "--chain=${CHAIN}",
      "--name=${NODE_NAME}",
      "--telemetry-url=wss://telemetry.parachain.robonomics.network/submit/ 0",
      "--base-path=/robonomics/base/",
      "--prometheus-external",
      "--state-pruning=archive",
      "--blocks-pruning=archive",
      "--rpc-external",
      "--rpc-cors=all",
      "--",
      "--sync=warp",
      "--prometheus-external"
    ]
